import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Digital business website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <>
    <Head>
    <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet" />
    </Head>
    <html lang="en" />
    <body>{children}</body>
    </>
  )
}